src/Entity/AddressBook.php
<?php

namespace App\Entity;

use App\Service\ImageUploader;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AddressBookRepository")
 */
class AddressBook
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @ORM\Column(type="text", length=255)
     * @Assert\NotBlank()
     */
    private $street;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $number;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $zip;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $country;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $phone;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank()
     * @Assert\Date()
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    public function getId(): int
    {
        return $this->id;
    }

    public function getFirstName()
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName()
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getStreet()
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getNumber()
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getZip()
    {
        return $this->zip;
    }

    public function setZip(int $zip)
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity()
    {
        return $this->city;
    }

    public function setCity(string $city)
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function setCountry(string $country)
    {
        $this->country = $country;

        return $this;
    }

    public function getPhone()
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBirthday()
    {
        return $this->birthday;
    }

    public function setBirthday($birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getFormattedBirthDay()
    {
        return $this->birthday->format('Y-m-d');
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPicturePath()
    {
        return ImageUploader::MAIN_DIRECTORY_PATH . DIRECTORY_SEPARATOR . ImageUploader::IMAGE_PATH . DIRECTORY_SEPARATOR . $this->getPicture();
    }
}

src/Controller/AddressBookController.php
<?php

namespace App\Controller;

use App\Entity\AddressBook;
use App\Events\AddressBookEvent;
use App\Events\AddressBookDeleted;
use App\Form\AddressBookFormType;
use App\Service\ImageUploader;
use Doctrine\DBAL\Exception\DatabaseObjectNotFoundException;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AddressBookController extends Controller
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var ImageUploader
     */
    private $imageUploader;
    /**
     * @var EventDispatcherInterface
     */
    private $dispatcher;

    public function __construct(
        EntityManagerInterface $entityManager,
        ImageUploader $imageUploader,
        EventDispatcherInterface $dispatcher
    )
    {

        $this->entityManager = $entityManager;
        $this->imageUploader = $imageUploader;
        $this->dispatcher = $dispatcher;
    }

    /**
     * @Route("/", name="address_book")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {
        $results = $this->entityManager->getRepository(AddressBook::class)->findAllAddressBooks();
        $addressBooks = $paginator->paginate($results, $request->query->getInt('page', 1));

        return $this->render(
            'address_book/index.html.twig',
            compact('addressBooks')
        );
    }

    /**
     * @Route("/address/book/create", name="address_book_create")
     * @param Request $request
     * @return Response
     */
    public function create(Request $request)
    {
        $addressBook = new AddressBook();
        $form = $this->createForm(AddressBookFormType::class, $addressBook);
        $result = $this->handleRequest($form, $request, $addressBook);
        if ($result) {
            $this->addFlash(
                'notice',
                'New record has been added successfully!'
            );

            return $this->redirectToRoute('address_book');
        }
        return $this->render(
            'address_book/create.html.twig',
            [
                'addressBookForm' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/address/book/{addressBook}/edit", name="address_book_edit")
     * @param AddressBook $addressBook
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function edit(AddressBook $addressBook, Request $request)
    {
        $form = $this->createForm(
            AddressBookFormType::class,
            $addressBook,
            ['method' => 'PUT']
        );
        $result = $this->handleRequest($form, $request, $addressBook);
        if ($result) {
            $this->addFlash('notice', 'Your changes were saved!');

            return $this->redirectToRoute('address_book');
        }

        return $this->render('address_book/create.html.twig', ['addressBookForm' => $form->createView()]);
    }

    /**
     * @Route("/address/book/{addressBook}", name="address_book_show",methods={"GET"})
     * @param AddressBook $addressBook
     * @return Response
     */
    public function show(AddressBook $addressBook)
    {
        $form = $this->createFormBuilder()
            ->setAction($this->generateUrl('address_book_delete', ['addressBook' => $addressBook->getId()]))
            ->setMethod('DELETE')
            ->getForm()->createView();

        return $this->render('address_book/show.html.twig', compact('addressBook', 'form'));
    }

    /**
     * @Route("/address/book/{addressBook}", name="address_book_delete",methods={"DELETE"})
     * @param AddressBook $addressBook
     * @return RedirectResponse
     */
    public function delete(AddressBook $addressBook)
    {
        try {
            $this->entityManager->remove($addressBook);
            $this->dispatcher->dispatch(
                AddressBookDeleted::class,
                new AddressBookDeleted($addressBook->getPicturePath())
            );
            $this->entityManager->flush();
            $this->addFlash(
                'notice',
                'Record deleted successfully!'
            );

            return $this->redirectToRoute('address_book');
        } catch (DatabaseObjectNotFoundException $exception) {

        }
    }

    private function handleRequest(FormInterface $form, Request $request, AddressBook $addressBook)
    {
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form['imageFile']->getData();
            $this->dispatcher->dispatch(AddressBookEvent::class, new AddressBookEvent($addressBook, $image));
            $this->entityManager->persist($addressBook);
            $this->entityManager->flush();

            return true;
        }

        return false;
    }
}

templates/address_book/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AddressBookController!{% endblock %}

{% block body %}
    <div class="col-8 mx-auto py-5">
        <h3>Create new contact</h3>
        {% form_theme addressBookForm 'bootstrap_4_layout.html.twig' %}
        {{ form_start(addressBookForm,{ attr: {novalidate: 'novalidate'}}) }}
        {{ form_widget(addressBookForm) }}
        {% if  addressBookForm.vars.value.picture|length %}
            <div class="w-25 mb-3">
                <img class="img-fluid rounded border border-dark p-1"
                     src="{{ asset(addressBookForm.vars.value.picturePath) }}"
                     alt="">
            </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
        {{ form_end(addressBookForm) }}
    </div>
{% endblock %}

templates/address_book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AddressBookController!{% endblock %}

{% block body %}
    <div class="col-12 mx-auto py-5">
        <h3>Contacts list</h3>
        {% for message in app.flashes('notice') %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        <table class="table table-striped table-bordered table-sm">
            <thead>
            <tr>
                <th class="th-sm">First name</th>
                <th class="th-sm">Last name</th>
                <th class="th-sm">Email</th>
                <th class="th-sm">Number</th>
                <th class="th-sm">Zip code</th>
                <th class="th-sm">Phone</th>
                <th class="th-sm">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for addressBook in addressBooks %}
                <tr>
                    <td>{{ addressBook.firstName }}</td>
                    <td>{{ addressBook.lastName }}</td>
                    <td>{{ addressBook.email }}</td>
                    <td>{{ addressBook.number }}</td>
                    <td>{{ addressBook.zip }}</td>
                    <td>{{ addressBook.phone }}</td>
                    <td class="text-center">
                        <a class="btn btn-info px-2 py-0"
                           href="{{ path('address_book_edit',{addressBook:addressBook.id}) }}"><i
                                    class="fa fa-edit text-light"></i></a>
                        <a class="btn btn-success px-2 py-0"
                           href="{{ path('address_book_show',{addressBook:addressBook.id}) }}"
                        ><i class="fa fa-eye text-light"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="navigation">
            {{ knp_pagination_render(addressBooks) }}
        </div>
    </div>
{% endblock %}

templates/address_book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AddressBookController!{% endblock %}

{% block body %}
    <div class="col-12 mx-auto py-5">
        <div class="card">
            <div class="card-header">
                Contact information
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ addressBook.firstName }}</li>
                    <li class="list-group-item">{{ addressBook.lastName }}</li>
                    <li class="list-group-item">{{ addressBook.email }}</li>
                    <li class="list-group-item">{{ addressBook.street }}</li>
                    <li class="list-group-item">{{ addressBook.number }}</li>
                    <li class="list-group-item">{{ addressBook.zip }}</li>
                    <li class="list-group-item">{{ addressBook.city }}</li>
                    <li class="list-group-item">{{ addressBook.country }}</li>
                    <li class="list-group-item">{{ addressBook.formattedBirthDay }}</li>
                    <li class="list-group-item">{{ addressBook.email }}</li>
                    <li class="list-group-item">{{ addressBook.phone }}</li>
                    {% if(addressBook.picture) %}
                        <li class="list-group-item">
                            <div class="w-25 mb-3">
                                <img class="img-fluid rounded border border-dark p-1"
                                     src="{{ asset(addressBook.picturePath) }}"
                                     alt="">
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="card-footer bg-transparent border-success">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <a class="btn btn-info" href="{{ path('address_book_edit',{addressBook:addressBook.id}) }}">
                    Edit Contact
                </a>
                <button type="submit" class="btn btn-danger">Delete Record</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}